name: Bug Report
description: Something works wrong?
labels: "needs triage,bug"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.

  - type: input
    id: commit
    attributes:
      label: Tool commit (or version)
      placeholder: git rev-parse HEAD
  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: python -V
    validations:
      required: true
  - type: input
    id: poetry_version
    attributes:
      label: Poetry Version (or pip)
      placeholder: poetry version (or pip version)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce
      description: Please provide steps to reproduce this bug.
      placeholder: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: sh-session

  - type: checkboxes
    id: checkboxes
    attributes:
      label: This is not duplicate.
      options:
        - label: In repository and internet there is no this (or same) error.
          required: true
